/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 facebook.gltf -t
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Curve007: THREE.Mesh
    Curve007_1: THREE.Mesh
  }
  materials: {
    ['default']: THREE.MeshStandardMaterial
    facebook: THREE.MeshStandardMaterial
  }
};

const Facebook = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('facebook.gltf') as GLTFResult
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve007.geometry} material={materials['default']} />
      <mesh geometry={nodes.Curve007_1.geometry} material={materials.facebook} />
    </group>
  );
};

export default Facebook;

useGLTF.preload('facebook.gltf');
