/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 facebook.gltf -t
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: any,
  materials: any,
};

const Facebook = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/spiderman.gltf') as GLTFResult
  console.log('🚀 ~ file: Facebook.tsx:17 ~ Facebook ~ materials:', materials)
  console.log('🚀 ~ file: Facebook.tsx:17 ~ Facebook ~ nodes:', nodes)
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.material} />
    </group>
  );
};

export default Facebook;

useGLTF.preload('/spiderman.gltf');
